### ISSUE TITLE
brandless.com

### ISSUE THREAD

**Issue by stokfredrik** [PortSwigger/turbo-intruder#10]
Issue identified on brandless.com/api/line_items/<idnumberofproduct>
Changing debug.py from THREADED to BURP results in successful reponses instead of "null"

```
POST /api/line_items/45184332 HTTP/1.1
Host: brandless.com
accept: application/json; version=1
Origin: https://brandless.com
User-Agent: stokzilla %s
content-type: application/json
Cookie: guest_token=redacted

{"quantity":1}
```
Running:
```
Burp Suite Professional v1.7.3.7
Turbo intruder V 1.0.3 (BAPP download)
Mac OS X, 10.14.2, 18C54
java.version, 1.8.0_112
```

**Comment by albinowax** [comment]
Hmm this works fine for me. What response do you get with Engine.BURP - is it a 404?

**Comment by stokfredrik** [comment]
yeah, my typical race setup (and the example one) gives me the null 4 issue

**Comment by albinowax** [comment]
What output do you get in the console or Extender->Extensions->Turbo Intruder->Errors?

**Comment by stokfredrik** [comment]
il have to get back on you on that.

**Comment by albinowax** [comment]
I've fixed a few network stack issues since this post so I'm closing it for now.
