### ISSUE TITLE
when using script "race.py", i got status-code 505

### ISSUE THREAD

**Issue by mumu0215** [PortSwigger/turbo-intruder#101]
while sending this request to race.py, it always gets 505 status code
<img width="612" alt="image" src="https://user-images.githubusercontent.com/40090857/171447638-c4656664-520a-4a19-a02d-58c6434b96f7.png">
<img width="453" alt="image" src="https://user-images.githubusercontent.com/40090857/171447683-76046b50-3ac2-494b-b253-a479c4f5b7a9.png">

**Comment by chain00x** [comment]
You can use http1.1

**Comment by mumu0215** [comment]
> You can use http1.1

i have done with it, but i really want to no why
dose it have some connections with some characteristic of http2.0？
