### ISSUE TITLE
No output showing on screen

### ISSUE THREAD

**Issue by fkoussa** [PortSwigger/turbo-intruder#105]
Hi!

Weird thing, suddenly stopped showing the output in the pane. Any idea?
![image](https://user-images.githubusercontent.com/40599884/175809057-70391695-9da7-473e-a89d-01f074a6d760.png)

Thanks

**Comment by albinowax** [comment]
Hi, to put a response in the table, use table.add() like in the examples. I guess your table.add() call got deleted.

**Comment by fkoussa** [comment]
@albinowax  Thanks
