### ISSUE TITLE
Would it be possible to implement the visualization of codes 404?

### ISSUE THREAD

**Issue by doverman22** [PortSwigger/turbo-intruder#111]
Turbo Intruder doesn't display responses with code 404.

My target has a different 404 response whether the file exists or not, so I need to be able to see 404s too, or at least filter for content-length of the reply or something of that nature.

**Comment by albinowax** [comment]
You can make Turbo Intruder display whatever you want by customising the code in the callback function. The easiest way to do this is using response decorators: https://github.com/PortSwigger/turbo-intruder/blob/master/decorators.md
