### ISSUE TITLE
Unique decorators don't work properly

### ISSUE THREAD

**Issue by ZPCA96** [PortSwigger/turbo-intruder#117]
Hello. Unique decorators don't work properly because incorrect getting successfulRequests attribute of req.engine instance in ScriptEnvironment.py. successfulRequests is attribute of req.engine.engine object, not req.engine.
![image](https://user-images.githubusercontent.com/100945838/199302400-8cd78ffb-e889-4561-bd4a-a2eb3d191bcb.png)

Can you fix?

**Comment by Kaabun** [comment]
Hello, first of all - thanks for the amazing extension. Secondly, there is any update about this problem (in my opinion unique decorators is the feature which could huge time saver)?

**Comment by albinowax** [comment]
This should be easy to patch - maybe you could have a go :)

**Comment by Kaabun** [comment]
If so, I'll give it a try :)

**Comment by Kaabun** [comment]
@albinowax fix proposed by @ZPCA96 is in my opinion correct (I locally made changes in `resources/ScriptEnvironment.py` file - from `req.engine.successfulRequests.intValue()` to `req.engine.engine.successfulRequests.intValue()` and after some testing I did't find any bug).
