### ISSUE TITLE
Can You Make disc_words.txt Public?

### ISSUE THREAD

**Issue by jgamblin** [PortSwigger/turbo-intruder#13]
Can you please upload this file to the repo?

https://github.com/PortSwigger/turbo-intruder/blob/aef8c02525b542ba2cdd87fd3f86410fcec38842/resources/examples/specialWordlists.py#L11

**Comment by albinowax** [comment]
It's mostly just raft-large-words from https://github.com/danielmiessler/SecLists/blob/master/Discovery/Web-Content/
