### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by cqrlhz** [PortSwigger/turbo-intruder#136]
turbo-intruder 1.40
java 11 

It can be successfully run and detected in burp, but it cannot be detected when it is placed in vps
java -jar turbo-intruder-all.jar user_password_brute.py burp.txt http://210.56.63.141:80 foobar
Please note that Turbo Intruder's SSL/TLS handling may differ slightly when run outside Burp Suite.
TURBO NOTICE: The input request appears to be using \n instead of \r\n as a line-ending. Consider changing your text-editor settings. Normalizing...  
ID | Word | Status | Wordcount | Length | Time
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.python.core.PySystemState (file:/root/turbo-intruder/turbo-intruder-all.jar) to method java.io.Console.encoding()
WARNING: Please consider reporting this to the maintainers of org.python.core.PySystemState
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Starting attack...
failed to read from clipboard
Aug 15, 2023 10:13:52 PM org.python.netty.util.internal.PlatformDependent <clinit>
INFO: Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
Establishing 30 connection to http://210.56.63.141:80...
Completed attack on http://210.56.63.141:80
Sent 99946 requests over 1025 connections in 34.89661 seconds
RPS: 2856

Reqs: 99946 | Queued: 0 | Duration: 35 | RPS: 2856 | Connections: 1025 | Retries: 0 | Fails: 0 | Next: null | Completed |

**Comment by albinowax** [comment]
Looks like you're trying to read data from the clipboard - try a local file instead.
