### ISSUE TITLE
Changing target in GUI mode

### ISSUE THREAD

**Issue by laxaa** [PortSwigger/turbo-intruder#14]
It is possible to specify the target/endpoint using the CLI in headless mode. But, it does not seem to be possible to modify the target when using the GUI version of turbo-intruder.

So far, the way of doing it is modifying the target in repeater or other tab and then to send to turbo-intruder, is there a better way of doing this ? Maybe adding a button to modify the target would make this more handy.

**Comment by albinowax** [comment]
Yes, you can modify the target by changing the 'endpoint' argument to RequestEngine. It's a string containing a protocol, domain and port eg 'https://example.com:443'.
