### ISSUE TITLE
Proxy Settings

### ISSUE THREAD

**Issue by zarkones** [PortSwigger/turbo-intruder#151]
Turbo Intruder does not respect Burp's proxy settings. It would just make a non-proxied request. Simple as that.

Btw, @albinowax  you're awesome! I'm a huge fan of backslash powered scanner.

**Comment by albinowax** [comment]
Yeah it will respect the proxy settings if you set engine=Engine.BURP or Engine.BURP2

Thanks! Always good to hear from a BPS fan!
