### ISSUE TITLE
Rate Limiting Vulnerability Feature

### ISSUE THREAD

**Issue by trapp3rhat** [PortSwigger/turbo-intruder#16]
How to find rate limiting vulnerability using Turbo intruder.

It is asking me to specify the wordlists everytime. here in same cases am not going to give payload from the wordlists or I would like to send the same request more than 1000 times. I want to run the same request with null payload.

This can able done through intruder in burp 
Kindly help me to understand this

**Comment by albinowax** [comment]
Look at the other examples in https://github.com/PortSwigger/turbo-intruder/tree/master/resources/examples
