### ISSUE TITLE
Connection Issues

### ISSUE THREAD

**Issue by ay-kay** [PortSwigger/turbo-intruder#2]
Turbo Intruder against the target domain [https://andreas-kurtz.de](https://andreas-kurtz.de) does not work for me. 
Engine.BURP works, Engine.THREADED returns 3x failed using [debug.py](https://github.com/PortSwigger/turbo-intruder/blob/master/resources/examples/debug.py).

__Diagnostics:__
```
java.home                        /Applications/Burp Suite Professional.app/Contents/PlugIns/jre.bundle/Contents/Home/jre
java.io.tmpdir                   /var/folders/vl/yq_8t_q144x7q0ty9sjb0m5w0000gn/T/
java.runtime.name                Java(TM) SE Runtime Environment
java.runtime.version             1.8.0_112-b16
java.specification.name          Java Platform API Specification
java.specification.vendor        Oracle Corporation
java.specification.version       1.8
java.vendor                      Oracle Corporation
java.vendor.url                  http://java.oracle.com/
java.vendor.url.bug              http://bugreport.sun.com/bugreport/
java.version                     1.8.0_112
...
os.arch                          x86_64
os.name                          Mac OS X
os.version                       10.14.3
```

**Comment by albinowax** [comment]
Thanks for the report. I've been able to partially replicate it - when I use OSX (with the latest version of Burp's platform installer which bundles Java 11), the first request succeeds but the two after both fail. I've just pushed a fix for this: https://github.com/PortSwigger/turbo-intruder/commit/ffdd4af903d912c436567eb259b83a6344162d05

Can you try the fix out and see if it works for you: https://github.com/PortSwigger/turbo-intruder/releases/tag/1.0.2

**Comment by ay-kay** [comment]
I confirm that it now works for me too. Thank you very much!

**Comment by albinowax** [comment]
Thanks for confirming, that's great news. I'll see about getting the bapp store version updated.
