### ISSUE TITLE
How to make requests with 3 injection points

### ISSUE THREAD

**Issue by trapp3rhat** [PortSwigger/turbo-intruder#22]
Hello Bro ,

Here I have modified the multipleParameters.py content to make the requests to the server with the 3 injection points. Here I want to use 3 different word lists for those injection points

The changes has been looks like below,
-------------------------------------------------------------------------------------------------
def queueRequests(target, wordlists):
    engine = RequestEngine(endpoint=target.endpoint,
                           concurrentConnections=5,
                           requestsPerConnection=100,
                           pipeline=False
                           )
    engine.start()

    for firstWord in open('/usr/share/dict/words'):
      for secondWord in open('/usr/share/dict/american-english'):
        for thirdWord in open('/root/user/wordlist/British-english'):
        engine.queue(target.req, [firstWord.rstrip(), secondWord.rstrip(), thirdWord.rstrip()])

def handleResponse(req, interesting):
    # currently available attributes are req.status, req.wordcount, req.length and req.response
    if req.status != 404:
        table.add(req)
------------------------------------------------------------------------------------------------

But I am getting the error like the attached image. It is possible to make the request with 3 injection points using turbo intruder if yes then kindly share the codes for that 

Thanks in advance !!

![Turbo_Intruder](https://user-images.githubusercontent.com/33062153/66339111-0dd97c80-e960-11e9-82b1-deffec957ea3.PNG)

**Comment by wdahlenburg** [comment]
You have the right idea. It looks like you are having issues with Python indentation. Add a few spaces after the third for loop.

```
for firstWord in open('/usr/share/dict/words'):
  for secondWord in open('/usr/share/dict/american-english'):
    for thirdWord in open('/root/user/wordlist/British-english'):
      engine.queue(target.req, [firstWord.rstrip(), secondWord.rstrip(), thirdWord.rstrip()])
```

**Comment by albinowax** [comment]
Yep that looks correct
