### ISSUE TITLE
Wordlist path parsing error in Windows

### ISSUE THREAD

**Issue by sushil-sharma** [PortSwigger/turbo-intruder#23]
![error](https://user-images.githubusercontent.com/12873801/66463732-4df14a00-ea9b-11e9-8e35-cbc10c3a710f.jpg)

Windows OS. Wordlist does not load

When try to use
for word in open('C:\_trx\api_wordlist-master\all11.txt'):

Get error:
'No such file or directory', 'c:\\_trx\x07pi_wordlist_master\x07ll11.txt'

Path c:\ is getting converted to c:\\
Letter 'a' is getting converted to 'x07

Tested in Windows 10 and Windows Server 2016
BurpSuite Professional v2.1.04

Attached screenshot

Request please check

**Comment by albinowax** [comment]
This is an error with the Python you've written. Unfortunately I don't provide support for user-written code.

**Comment by lifesfun101** [comment]
I actually have the same problem, i only replaced the worldlist portion of the script on windows and i get similar error

**Comment by rashedgbd** [comment]
Just change the path to 'C:/_trx/api_wordlist-master/all11.txt' like this. Change '\' to '/'
