### ISSUE TITLE
Add numbers

### ISSUE THREAD

**Issue by MrSol0** [PortSwigger/turbo-intruder#25]
Hey, i want to filter multiple tickets in my system, so i want to use your plugin, i usually use "intruder" and i select the place and go to "payloads", select payload type "Numbers" and edit From and To, and Step, is it possible to have such thing on your system, knowing that i have about 1.8m tickets, from 1 to 1.8m, and many thanks, crypto donations will be sent.

**Comment by albinowax** [comment]
This is absolutely possible - just learn the basics of Python.
