### ISSUE TITLE
In commandline mode, table.add throws an exception with labels

### ISSUE THREAD

**Issue by maurosoria** [PortSwigger/turbo-intruder#26]
Hello!

I was launching an script (works perfectly with burp) in headless mode an it throws this exception:

> Error, check extender for full details: Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "<string>", line 42, in queueRequests
> TypeError: queue() got an unexpected keyword argument 'label'

Is it possible that 'label' argument does not work in headless mode? Is not supported or a bug?

Regards,
Mauro

**Comment by albinowax** [comment]
Are you sure you're using the same version of turbo intruder in headless mode as you are within burp? Older versions of turbo intruder don't support labels.
