### ISSUE TITLE
How to save turbo intruder results?

### ISSUE THREAD

**Issue by an0th3rhuman** [PortSwigger/turbo-intruder#27]
I couldnt find any option to save turbo intruder results. # #

**Comment by albinowax** [comment]
Select the table rows you want, then right click and use 'Add to sitemap' or 'Report as issue'

**Comment by PushkraJ99** [comment]
https://security.stackexchange.com/questions/155434/how-do-i-extract-data-from-response-in-burp-suite-intruder
