### ISSUE TITLE
Using turbo intruder for race condition

### ISSUE THREAD

**Issue by g33kyshivam** [PortSwigger/turbo-intruder#28]
Hello, I just want to have some more information regarding using turbo intruder for race condition. 

In this report https://hackerone.com/reports/759247
 He mentions that a header needs to be added 
_Now set the external HTTP header ```x-request: %s -``` This is needed by the turbo intruder_

Is this some extra feature, I did over the portswigger turbo intruders blog but couldn't find this header

Need some more information regarding this :)

**Comment by albinowax** [comment]
The header name is meaningless.

**Comment by cyanpiny** [comment]
> The header name is meaningless. It's just a way to get `%s` into the request (which is the input marker).

Can I use this feature by defining a unique value? Is it possible to race using different values in each request?
Sample:
Sample:
x-request: 1
x-request: 2
x-request: 3
x-request: 4
...
