### ISSUE TITLE
Follow redirects when using the standalone JAR

### ISSUE THREAD

**Issue by SpenGietz** [PortSwigger/turbo-intruder#33]
Is this possible?

I need to be using the standalone JAR (so I can't use Burp's built-in settings) and I need the requests to follow 301s and 302s, but I'm not finding anywhere that would help configure that or even seeing where I would manually insert some code to make a second request to the "Location" header.

Thanks!

Edit: In my case, the 301s/302s may redirect to different hosts, so it might not be possible

**Comment by albinowax** [comment]
You can implement support for redirects in the handleResponse function. However it's not the simplest task in the world (especially for cross-domain redirects) and this is a common query, so I might code up an example script for it.

**Comment by SpenGietz** [comment]
Thanks @albinowax, I'll see what I can do in handleResponse!
