### ISSUE TITLE
observedWords doesn't seem to work

### ISSUE THREAD

**Issue by tavdog** [PortSwigger/turbo-intruder#35]
I've tried getting observedWords to work with the specialWords example script but it never actually uses any of the observed history.  Is there a trick to get observedWords to populate ?  The target I'm using has been added to scope.

**Comment by albinowax** [comment]
Good question! Turbo Intruder records observed words during passive scanning - I guess you have the normal 'passive scan as you browse' task turned off? I'll add this to the documentation.
