### ISSUE TITLE
Low RPS

### ISSUE THREAD

**Issue by Raywando** [PortSwigger/turbo-intruder#36]
Hello,
Idk if I'm doing something wrong here, but I'm not getting more than 4 RPS at minimum settings while as the demo video, it is supposed to be much higher.

```
def queueRequests(target, wordlists):
    engine = RequestEngine(endpoint=target.endpoint,
                           concurrentConnections=1,
                           requestsPerConnection=1,
                           pipeline=False
                           )

    engine.start()

    for i in range(3, 8):
        engine.queue(target.req, randstr(i), learn=1)
        engine.queue(target.req, target.baseInput, learn=2)

    for word in range(10000000, 40000000):
    #for word in open('D:\dicc.txt'):
        engine.queue(target.req, word)


def handleResponse(req, interesting):
    if 'sometext' in req.response:
        table.add(req)
```

![8pY6gEtGlV](https://user-images.githubusercontent.com/33800255/80933961-84dbd400-8dce-11ea-8429-5ed0fa9f83b7.png)

Any ideas? Thank you <3

**Comment by albinowax** [comment]
You need to change concurrentConnections and requestsPerConnection

**Comment by Raywando** [comment]
Thanks for the guidance (: 

But i have already done that and i think it's irrelevant, even for minimum settings (concurrentConnections=1, requestsPerConnection=1, pipeline=false) 3 RPS doesn't make sense according to the video James made where he got like 80 RPS with these same settings. 

However, optimizing the settings (concurrentConnections=20, requestsPerConnection=400, pipeline=True) the RPS i got was not more than 300 RPS

**Comment by albinowax** [comment]
It depends on the target site, your own network, etc. I can't really offer in-depth support here unfortunately.

**Comment by Raywando** [comment]
I thought it could be a problem with burp suit or something I'm not aware of. 
That's understandable though, your efforts are appreciated.

**Comment by Akash-Hamal** [comment]
def queueRequests(target, wordlists):
    engine = RequestEngine(endpoint=target.endpoint,
                           concurrentConnections=20,
                           requestsPerConnection=100,
                           pipeline=True
                           )
    engine.start()                       

    for word in open('/usr/share/dict/2fa.txt'):
        engine.queue(target.req, word.rstrip())


def handleResponse(req, interesting):
    # currently available attributes are req.status, req.wordcount, req.length and req.response
    if req.length > 456:
        table.add(req)



Here is the script in turbo intruder, and I am getting about 500-600 RPS not even near to 1k. Watched ur video, tried ur settings didn't work! If there are any tips to get even 1k RPS i would be happy as it means  6 digits OTP can be bruteforced in an hour :D

**Comment by Akash-Hamal** [comment]
And as the requests are growing, the RPS keeps dropping!

**Comment by albinowax** [comment]
The speed depends on the target server, your connection, and many other factors.
