### ISSUE TITLE
Server stops responding

### ISSUE THREAD

**Issue by Markc1488** [PortSwigger/turbo-intruder#37]
Love this project first of all and good work guys. My issue is I’m trying to post two seperate fields of data which I got working but it will start to send all the posts then I’m banned after about 100 request posts. I can post my coding when I get home but what I’m doing is pulling from datalist1 and datalist2. How exactly can I either queue the posts which slows everything down or am I able to post say using a different proxy for each 100 posts?

**Comment by albinowax** [comment]
Try time.sleep
