### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ratinnatin** [PortSwigger/turbo-intruder#38]
Hey,

Is it possible to add 30 payloads as a wordlist?. If yes then how we can add it?

Regards

**Comment by albinowax** [comment]
Yes, you need to learn some basic Python.

**Comment by ratinnatin** [comment]
Hey,

Could you please provide the command here?. That'd be appreciated.

Regards

**Comment by albinowax** [comment]
Nope sorry, it's not really practical for me to help all users of Turbo Intruder. It's a tool for expert users who are familiar with Python or willing to learn it.
