### ISSUE TITLE
show empty after click attack

### ISSUE THREAD

**Issue by tuhaolam** [PortSwigger/turbo-intruder#39]
![image](https://user-images.githubusercontent.com/10894348/83244915-9f894900-a1d2-11ea-9f2a-cbdd02873267.png)

**Comment by tuhaolam** [comment]
version of my burpsuite is professional v2020.2

**Comment by albinowax** [comment]
This is probably an issue with your script and/or request. To confirm where the issue lies, you can apply the steps in https://github.com/PortSwigger/turbo-intruder/blob/master/resources/examples/debug.py

**Comment by tuhaolam** [comment]
> This is probably an issue with your script and/or request. To confirm where the issue lies, you can apply the steps in https://github.com/PortSwigger/turbo-intruder/blob/master/resources/examples/debug.py

It works! I have changed engine=Engine.THREADED to engine=Engine.BURP.

**Comment by albinowax** [comment]
Great to hear. If possible, could you let me know the target domain? No worries if not.
