### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by SbIm** [PortSwigger/turbo-intruder#40]
As the [debug script](https://github.com/PortSwigger/turbo-intruder/blob/master/resources/examples/debug.py) described, I post my request here.

Without Engine.BURP Turobo Intruder won't work.

```
POST /api/like/create.json?sourceType=TIMELINE&homeId={} HTTP/1.1
Host: timeline.line.me
Connection: keep-alive
Content-Length: 122
Accept: application/json, text/plain, */*
X-Timeline-WebVersion: 1.18.2
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36
Content-Type: application/json;charset=UTF-8
Origin: https://timeline.line.me
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: []
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,ja;q=0.7,zh-TW;q=0.6,pl;q=0.5
Cookie: []

{...}
```
Tell me if more info is necessary.

**Comment by SbIm** [comment]
Well,I've to say at first it doesn't work,
when I changed it to Engine.BURP, works.
And I change it back with engine=Engine.THREADED, it works this time.

**Comment by albinowax** [comment]
Sorry, I can't replicate getting that 400 Bad Request response. I really need a full/unredacted request to be able to fix this kind of issue, or at least one that triggers the behaviour you are describing.

I'm going to close this but feel free to reopen if you have still able to replicate this and provide a request that triggers it.
