### ISSUE TITLE
Mismatched input

### ISSUE THREAD

**Issue by r3curs1v3-pr0xy** [PortSwigger/turbo-intruder#43]
Whenever I start this with correct path of wordlist, it says "SyntaxError:("mismatched input "expecting DEDENT",('<string>',9,5,' engine.start()\n'))

**Comment by albinowax** [comment]
This looks like there's an error in the Python script introduced by your edit. I'd suggest learning the basics of Python before trying to use Turbo Intruder - it'll make life much easier.

**Comment by r3curs1v3-pr0xy** [comment]
def queueRequests(target, wordlists):
    engine=RequestEngine(endpoint=target.endpoint,
                         concurrentConnections=3,
                         requestsPerConnection=10,
                         pipeline=True
                         )

      
     engine.start()

     for i in range(3,8):
         engine.queue(target.req, randstr(i), learn=1)
         engine.queue(target.req, target.baseInput, learn=2)

     for word in open('/home/devil/Desktop/custom.txt'):
         engine.queue(target.req,word.strip())


def handleResponse(req, interesting):
    if interesting:
       table.add(req)

**Comment by r3curs1v3-pr0xy** [comment]
I couldn;t find any mistake here but still the issue is same?
