### ISSUE TITLE
engine.start() no longer in code?

### ISSUE THREAD

**Issue by joefizz** [PortSwigger/turbo-intruder#50]
I am using Turbo-Intruder for the first time and following your LevelUp video.  When you use it in the video there is a engine.start() call in the turbo intruder code, however when I use it locally this does not exist.  Turbo intruder still works and perofrms as expected however, you mention moving this engine.start() call lower in the code when attempting race conditions.  Has the code changed around this?

```
# Find more example scripts at https://github.com/PortSwigger/turbo-intruder/blob/master/resources/examples/default.py
def queueRequests(target, wordlists):
    engine = RequestEngine(endpoint=target.endpoint,
                           concurrentConnections=5,
                           requestsPerConnection=100,
                           pipeline=True
                           )

    for i in range(3, 8):
        engine.queue(target.req, randstr(i), learn=1)
        engine.queue(target.req, target.baseInput, learn=2)

    for word in open('/path/to/wordlist):
        engine.queue(target.req, word.rstrip())


def handleResponse(req, interesting):
    if interesting:
        table.add(req)
```

**Comment by albinowax** [comment]
Good question! engine.start is no longer necessary. If you want to sync requests to help trigger a race condition, use the gate system shown in examples/race.py
