### ISSUE TITLE
Keyboard shortcuts don't in MacOS with Nimbus 

### ISSUE THREAD

**Issue by wdahlenburg** [PortSwigger/turbo-intruder#51]
Ctrl-C (copy), Ctrl-X (cut), Ctrl-V (paste), and Ctrl-A (select all) are not functioning with the latest update to include the python editor on the GUI. 

The slow option is to right click and choose one of Cut, Copy, Paste, Delete, or Select All.

Can these shortcuts be enabled with the new editor?

**Comment by albinowax** [comment]
Interesting, they work for me. What platform are you on?

**Comment by albinowax** [comment]
Ah I see it doesn't work on MacOS. Might be because I disable their keymap to work around a library bug.

**Comment by wdahlenburg** [comment]
Correct. I should have specified MacOS. I checked on Win 10 and Ubuntu 20 and the shortcuts work fine.

**Comment by albinowax** [comment]
I found a workaround: use Darcula :)

**Comment by wdahlenburg** [comment]
Is Burp applying some behind the scenes magic with Darcula? I tested out the other available Burp themes and was also able to use shortcuts with the Mac OS X theme.

**Comment by albinowax** [comment]
I think it's the other way around - Nimbus is doing something behind the scenes that breaks this. Core Burp Suite probably has a workaround for this, but the editor I'm using doesn't.

**Comment by w9w** [comment]
++. I've just came here to fill an issue

**Comment by wdahlenburg** [comment]
@albinowax Not sure when the cut over happened with themes, but this no longer appears to be an issue. Light and dark modes support copy, cut, paste, etc shortcuts on MacOS.
