### ISSUE TITLE
Connect Error

### ISSUE THREAD

**Issue by antichown** [PortSwigger/turbo-intruder#52]
![errrr](https://user-images.githubusercontent.com/4655942/93275685-38fe5a00-f7c6-11ea-8dfa-760c532b2c9e.png)

plugin shuts itself down when website isn't connected

**Comment by albinowax** [comment]
What do you think should happen instead?

**Comment by antichown** [comment]
> What do you think should happen instead?

if there's a mistake, I'd like it to continue because I'm experimenting with multihost

**Comment by albinowax** [comment]
Ah that makes sense. This exception is coming from your code - that's why it says "User Python error". So you simply need to catch the exception yourself.
