### ISSUE TITLE
Need a little help

### ISSUE THREAD

**Issue by Tireiron1488** [PortSwigger/turbo-intruder#54]
I am trying to figure out where i did wrong here in my script please see attached. It is obviously working the first 20 requests or so then erroring the rest.

def queueRequests(target, wordlists):

    engine = RequestEngine(endpoint=target.endpoint,

                           concurrentConnections=5,

                           requestsPerConnection=2,

                           pipeline=False

                           )

    for i in range(3, 8):

        engine.queue(target.req, randstr(i), learn=1)

        engine.queue(target.req, target.baseInput, learn=2)

    for txtGiftCardNumber in open("d:60501101.txt"):

        engine.queue(target.req, txtGiftCardNumber.rstrip())

    engine.start()

def handleResponse(req, interesting):

    if interesting:

        table.add(req)

**Comment by albinowax** [comment]
Unfortunately since Turbo Intruder lets you write arbitrary Python, there's an infinite number of potential problems so I can't realistically provide personal support to everyone who has a script issue.
