### ISSUE TITLE
'Attack' causes a UI deadlock on MacOS, when '.NET Beautifier' is loaded

### ISSUE THREAD

**Issue by albinowax** [PortSwigger/turbo-intruder#55]
No idea why.

**Comment by zombietango** [comment]
Definitely a hard confirm on this issue. Thanks for mentioning this, it was driving me insane wondering what was going on.

**Comment by gujjuboy10x00** [comment]
same issue for me too!

**Comment by albinowax** [comment]
This has been patched in Burp 2020.11: https://portswigger.net/burp/releases/professional-community-2020-11
