### ISSUE TITLE
"Choose scripts dir" doesn't see files

### ISSUE THREAD

**Issue by w9w** [PortSwigger/turbo-intruder#57]
"Choose scripts dir" doesn't see files; they are not loading when we click on "open." OS macOS Catalina 10.15.6 (19G73).

**Comment by w9w** [comment]
Before the fix, the only solution to quickly access custom scripts is to copy them and paste to the editor using a mouse and clicks since shortcuts are not working, too.

**Comment by albinowax** [comment]
Do the filenames end in .py?

You can still copy+paste with the keyboard as noted here: https://github.com/PortSwigger/turbo-intruder/issues/51

**Comment by w9w** [comment]
@albinowax, they had .txt extension, I renamed to .py, and it works now. Thank you, I'm closing a ticket.
