### ISSUE TITLE
Standalone use of burp intruder

### ISSUE THREAD

**Issue by shadowzoom** [PortSwigger/turbo-intruder#59]
I want to check via turbo burp intruder list of urls for 200 status code where list is:
site1.com/index123.php
site2.com/index123.php
site3.com/index123.php

Any tips how to do that?

**Comment by albinowax** [comment]
Sorry, as you can probably imagine, I don't have time to individually tutor people in how to use tools I've released. Try learning Python and looking at the example scripts here: https://github.com/PortSwigger/turbo-intruder/tree/master/resources/examples
