### ISSUE TITLE
Update CSRF tokens

### ISSUE THREAD

**Issue by sdcampbell** [PortSwigger/turbo-intruder#6]
Is there any way to update CSRF tokens using Turbo Intruder? Thanks

**Comment by albinowax** [comment]
As mentioned, you use the callback function to extract tokens and queue up more requests: https://github.com/PortSwigger/turbo-intruder/blob/master/resources/examples/recursive.py

I'll leave this ticket open for now as I'm planning an update to make token extraction easier.

**Comment by albinowax** [comment]
I'm canning the easier-token-extraction update for now - it's quite fiddly and I've got higher priority stuff to do.
