### ISSUE TITLE
Is it possible to use random strings in Race?

### ISSUE THREAD

**Issue by cyanpiny** [PortSwigger/turbo-intruder#63]
edited examples/race.py
```
def queueRequests(target, wordlists):
    engine = RequestEngine(endpoint=target.endpoint,
                           concurrentConnections=30,
                           requestsPerConnection=100,
                           pipeline=False
                           )

    # the 'gate' argument blocks the final byte of each request until openGate is invoked
    for i in range(30):
        engine.queue(target.req, randstr(i), target.baseInput, gate='race1')

    # wait until every 'race1' tagged request is ready
    # then send the final byte of each request
    # (this method is non-blocking, just like queue)
    engine.openGate('race1')

    engine.complete(timeout=60)


def handleResponse(req, interesting):
    table.add(req)

```
![Untitled](https://user-images.githubusercontent.com/41749543/104205043-fcbecb80-543e-11eb-86dc-1a67a51e299f.jpg)

x-req: %s Returns an empty value. When I try something like the above, it gives an error. Is it possible to add a random string to the request?

**Comment by albinowax** [comment]
This is definitely possible. Unfortunately I can't realistically provide personal support to everyone who has trouble writing Python.

**Comment by cyanpiny** [comment]
> This is definitely possible. Unfortunately I can't realistically provide personal support to everyone who has trouble writing Python.

Do I have to add extra code to this? I think it used to do this by default.
