### ISSUE TITLE
Python UnicodeEncode  Error

### ISSUE THREAD

**Issue by Die-Mannschaft** [PortSwigger/turbo-intruder#64]
I cant run Turbo Intruder
![2021-01-14](https://user-images.githubusercontent.com/74534547/104603269-3e9b7c00-56a2-11eb-9c01-215de3fcd935.png)

**Comment by RitikV** [comment]
It is also showing this to me, I don't know what to do.

**Comment by OmarJAhmad** [comment]
hi , anyone fix it ? @albinowax

**Comment by OmarJAhmad** [comment]
![image](https://user-images.githubusercontent.com/42843641/132018067-a31956f5-6916-406f-8bfe-d9b09f4d5fa2.png)

**Comment by OmarJAhmad** [comment]
try to change the wordlist
