### ISSUE TITLE
SAML Raider + Turbo Intruder = deadlock

### ISSUE THREAD

**Issue by adriendb** [PortSwigger/turbo-intruder#65]
Burp Pro version 2020.6 
Using this script : https://nathandavison.com/blog/haproxy-http-request-smuggling
Against HAProxy
The funny thing is that Turbo Intruder works fine when I disable all other extensions
Any way to troubleshoot which one is having the problem?

**Comment by adriendb** [comment]
We have it narrowed down to a conflict with SAML Raider 1.3.0 and Turbo Intruder 1.1.3

**Comment by albinowax** [comment]
Can you try updating Burp Suite and see if that fixes it?

**Comment by adriendb** [comment]
Still hangs with Burp Suite Pro v2021.2, SAML Raider v1.4.0, and Turbo Intruder v1.1.3.

**Comment by albinowax** [comment]
Thanks, that's concerning, we'll take a look.

**Comment by melardev** [comment]
Hi, I have this issue for at least 2 months now, I thought it was a problem on a Linux PC I had, now I have another Linux, same issue, however on Windows, it worked fine ... I would be happy to be a "beta tester" for this issue because I use turbo intruder a lot and now I can't on my main PC.

**Comment by albinowax** [comment]
One of my more competent colleagues has identified the cause of this so I'll hopefully be able to get a patch out tomorrow.

**Comment by melardev** [comment]
Since both plugins are open-source, if the root cause of that deadlock does not involve proprietary source code, would you mind sharing the root cause of this? so we don't make the same mistake on other plugins you may write, or detect this easily while reading other plugins?

**Comment by albinowax** [comment]
I've just push 1.1.4 which fixes this, it'll land in the bapp store shortly.
