### ISSUE TITLE
 Chinese response is displayed as a question mark & Chinese response can't matched

### ISSUE THREAD

**Issue by superboy-zjc** [PortSwigger/turbo-intruder#67]
![image](https://user-images.githubusercontent.com/60600792/109480520-95281280-7ab6-11eb-82cf-f85310a9dfdb.png)

![image](https://user-images.githubusercontent.com/60600792/109449453-70667780-7a83-11eb-9c02-b11da69ee126.png)
![image](https://user-images.githubusercontent.com/60600792/109449493-8f650980-7a83-11eb-8627-3a1362be37b6.png)

**Comment by q0l** [comment]
@albinowax 

`print "запрос".encode("hex") = 3f3f3f3f3f3f`

Fix?

**Comment by albinowax** [comment]
I'd like to fix this, but don't know how :)

**Comment by q0l** [comment]
> I'd like to fix this, but don't know how :)

I don't know either, but maybe you need to look this way.

```
reload(sys)
sys.setdefaultencoding('utf-8')
```
or `PyString str = new PyString
`

**Comment by Baikeryoyo** [comment]
> > 我想解决此问题，但不知道如何:)
> 
> 我也不知道，但也许您需要这样看。
> 
> ```
> reload(sys)
> sys.setdefaultencoding('utf-8')
> ```
> 
> 或者 `PyString str = new PyString `

This method doesn't work

**Comment by superboy-zjc** [comment]
Thank u bro.I'll try it.

**Comment by albinowax** [comment]
I think I got this patched in the end.
