### ISSUE TITLE
Make code editor respect Burp's configured font size

### ISSUE THREAD

**Issue by lnxdork** [PortSwigger/turbo-intruder#71]
I have set the font options in burp to work well with a 4k monitor. 
The python code displayed in the turbo-intruder panel does not display using the font sizes set in burp.

The image below actually looks better than my monitor :)

![turbo](https://user-images.githubusercontent.com/40716638/118509256-e0d57a00-b6fd-11eb-8076-7a59a9ed4c8b.png)

**Comment by defparam** [comment]
Hey @lnxdork ,

Making Turbo Intruder follow suit with Burp's global font settings may not be workable today, however I have a workaround in which you can patch `turbo-intruder-all.jar` to customize the theme/font/fontsize of the rsyntaxtextarea component thus allowing you to customize the code editor's font settings.

Turbo Intruder applies a dark.xml theme when it detects burp is using the Darcula theme:
```java
if (UIManager.getLookAndFeel().getID().contains("Dar")) {
	val `in` = javaClass.getResourceAsStream("/org/fife/ui/rsyntaxtextarea/themes/dark.xml")
	try {
		val theme = Theme.load(`in`)
		theme.apply(textEditor)
	} catch (ioe: IOException) {
		Utils.out(ioe.toString())
		ioe.printStackTrace()
	}
}
else {
	textEditor.highlightCurrentLine = false
}

```

The steps are as follows in linux/WSL:
1) Go to the directory that contains `turbo-intruder-all.jar`, for me in WSL it was: `cd /mnt/c/Users/Evan/AppData/Roaming/BurpSuite/bapps/9abaa233088242e8be252cd4ff534988/build/libs`
2) Extract the rsyntaxtextarea dark theme: `unzip turbo-intruder-all.jar 'org/fife/ui/rsyntaxtextarea/themes/dark.xml' -d ./`
3) Open `./org/fife/ui/rsyntaxtextarea/themes/dark.xml` in a text editor and customize/add the `<baseFont family="..." size="13"/>` tag
4) Save the file
5) Patch it into Turbo Intruder by running: `zip -ru turbo-intruder-all.jar ./org/fife/ui/rsyntaxtextarea/themes/dark.xml`
6) Place burp in Darcula Mode (User options -> Display -> Look and feel)
7) Reload Turbo Intruder in the Extender tab
8) Send a request to Turbo Intruder

At this point you should see your custom Dark theme settings applied to the Code Editor component of Turbo Intruder

**Comment by defparam** [comment]
Unfortunately this hack only works in Dark mode due to the fact that the dark.xml theme for rsyntaxtextarea is loaded for proper syntax highlighting support in darcula. For all other burp themes it appear none of the rsyntaxtextarea xml themes are used (even though some say default). This hack won't work for the burp theme you are using in your screenshot. We would have to re-compile the java to pull in the default.xml theme for non-dark mode. Hope this helps

**Comment by albinowax** [comment]
Getting Burp's configured font size is tricky so I've added a setting for this accessible via the menu bar.
