### ISSUE TITLE
Chinese display garbled code

### ISSUE THREAD

**Issue by Baikeryoyo** [PortSwigger/turbo-intruder#73]
![image](https://user-images.githubusercontent.com/57838797/118623834-3479bd80-b7fb-11eb-9e2f-1ccc6416146f.png)

**Comment by albinowax** [comment]
Dupe of https://github.com/PortSwigger/turbo-intruder/issues/67

**Comment by Baikeryoyo** [comment]
> [＃67的](https://github.com/PortSwigger/turbo-intruder/issues/67)重复[](https://github.com/PortSwigger/turbo-intruder/issues/67)

The problem has not been solved

**Comment by albinowax** [comment]
I know, but having duplicate issues doesn't help
