### ISSUE TITLE
HTTP/2 breaks Turbo intruder

### ISSUE THREAD

**Issue by floyd-fuh** [PortSwigger/turbo-intruder#77]
Hey James,

This is more a fyi than anything else. I spent 1.5 hours trying to figure out why Turbo Intruder is so broken and Burp works. HTTP/2 was the problem. Changing to HTTP/1.1 in the request fixed everything. You might want to work on it or at least warn or auto-downgrade to 1.1.

cheers
floyd

**Comment by albinowax** [comment]
Thanks, yep there's a fix coming shortly.

**Comment by albinowax** [comment]
This should be fixed now
