### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by Hipapheralkus** [PortSwigger/turbo-intruder#8]
Is it currently possible to use CLI to set up proxy for requests? 
Or is there some other way, in case I want to populate Burp proxy history with requests+responses? Even if they would be duplicate for re-transmission.
Thanks

**Comment by Hipapheralkus** [comment]
yes, having them in sitemap would work. Is that a possibility at this point?

**Comment by albinowax** [comment]
It isn't possible right now but I can probably make it possible.

**Comment by albinowax** [comment]
I've just made a new release: https://github.com/PortSwigger/turbo-intruder/releases/tag/1.0.3a

In this, you can add items into the sitemap from your jython callback using callbacks.addToSiteMap(req.getBurpRequest())
