### ISSUE TITLE
Smuggle attack (CL.TE) not working with Turbo Inturder

### ISSUE THREAD

**Issue by DirtyBull** [PortSwigger/turbo-intruder#81]
Related environment information:
java.version                     16.0.2
java.version.date                2021-07-20
java.vm.version                  16.0.2+7-67
os.arch                          amd64
os.name                          Linux
os.version                       5.10.0-kali9-amd64
Burp Version                     2021.5.3
Build Number                     8265
HTTP Request Smuggler Version 2.0
Updated  05 Aug 2012
Turbo Intruder Version    1.21
Updated   11 Aug 2021

Issue description:
1. Right click on the 1st request of the smuggling issue found from the dashboard of burp:   Extensions -> Smuggle attack (CL.TE)
2. Then jump to Turbo Intruder with predefined script as showing below (Only modified prefix to "G"):
![Screenshot_1](https://user-images.githubusercontent.com/86283084/129477014-76dcd173-d7fa-4885-978a-f1fbcc26f48f.png)
3. Click Attack button but then it hanged with following error:
![error](https://user-images.githubusercontent.com/86283084/129477122-1c8218ab-e132-452b-8254-7bdf71d419b6.png)
4. Change parameter to engine=Engine.THREADED from engine=Engine.BURP. It's then working as expected:
![Screenshot_3](https://user-images.githubusercontent.com/86283084/129477229-0adb707c-b41e-49c6-b74b-1ebf96446d71.png)

Not sure if it should be the issue of the predefined script of the Smuggler or the Intruder should be compatible with that script.
Thank you~

**Comment by albinowax** [comment]
Thanks, I'll take a look

**Comment by albinowax** [comment]
I can't replicate the 'clicking attack doesn't work' issue you saw. The stack trace is unrelated, but I've fixed that.
