### ISSUE TITLE
Turbo Intruder Converts High-Order Bytes To UTF-8

### ISSUE THREAD

**Issue by Murdochcb** [PortSwigger/turbo-intruder#82]
It appears that Turbo Intruder is converting any high-order byte (0x80-0xFF) of the request template or injected parameters to UTF-8 representation, rather than respecting the literal input. This results in the actual request sent not matching the intended request.

For example, consider the following POST template, and script:

```
GET / HTTP/2
Host: [HOSTNAME_HERE]
Foo: bar ¡¢
Baz: %s


```
```
def queueRequests(target, wordlists):
   engine = RequestEngine(endpoint='https://[HOSTNAME_HERE]:443',
                          concurrentConnections=1,
                          requestsPerConnection=1,
                          engine=Engine.HTTP2,
                          pipeline=False
                         )

   engine.queue(target.req, ["qux\xBC\xBD\xBE"])

def handleResponse(req, interesting):
    table.add(req)
```

In this case, the expected request should have the `Foo` header equal to `bar\xA0\xA1\xA2`, and the `Baz` header equal to `qux\xBC\xBD\xBE`.

Submitting the attack results in the following request sent:
```
GET / HTTP/2
Host: [HOSTNAME_HERE]
Foo: barÂ Â¡Â¢
Baz: quxÂ¼Â½Â¾

```

Where `Foo` is equal to `bar\xC2\xA0\xC2\xA1\xC2\xA2` and `Baz` is equal to `quz\xC2\xBC\xC2\xBD\xC2\xBE`

**Comment by albinowax** [comment]
Thanks for the report, I've investigated this and patched it in 1.22
