### ISSUE TITLE
I'm Trying To Use multiHost.py Script With HTTP/2 Engine But I Can't So Can You Help Me 

### ISSUE THREAD

**Issue by 0xAwali** [PortSwigger/turbo-intruder#83]
I'm Trying To Use This Script With HTTP/2 Engine , But It's Complected AND I Don't Know How To Do This
```
def queueRequests(target, wordlists):
    req = '''GET / HTTP/1.1
Host: %s
Connection: keep-alive

'''
    engines = {}
    for domain in open('/tmp/domains'):
        domain = domain.rstrip()
        engine = RequestEngine(endpoint='https://'+domain+':443')
        engines[domain] = engine

    for i in range(3, 8):
        for (domain, engine) in engines.items():
            engine.queue(req, randstr(i)+'.'+domain, learn=1)

    for word in open('/tmp/words'):
        word = word.rstrip()
        for (domain, engine) in engines.items():
            engine.queue(req, word+'.'+domain)


def handleResponse(req, interesting):
    if interesting:
        table.add(req)
```
So Can You Help Me To Create This One By Using HTTP/2 Engine ?

**Comment by 0xAwali** [comment]
So After Reading The Documentation That @albinowax Wrote Its Yesterday , Finally I Know How To Play With Turbo-Intruder Now , So I'm Trying To Automate This One On Large Scale By Using Wordlist Contains 30K subdomains 

![Screenshot_2021-09-03_11_40_35](https://user-images.githubusercontent.com/54332136/131985650-6e1ffa0b-e93c-4f28-acf8-fd951160af76.png)

So Here I Need To Combine [multiHost.py](https://github.com/PortSwigger/turbo-intruder/blob/master/resources/examples/multiHost.py) AND [multipleParameters.py](https://github.com/PortSwigger/turbo-intruder/blob/master/resources/examples/multipleParameters.py) Scripts Together So Here Is My Code
```

def queueRequests(target, wordlists):
    req = '''GET / HTTP/2
:authority: %s
host: %s.me.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
'''

    engines = {}
    for domain in open('/home/mahmoud/test.txt'):

        domain = domain.rstrip()

        engine = RequestEngine(endpoint='https://'+domain+':443',
                               concurrentConnections=5,
                               requestsPerConnection=1,
                               engine=Engine.BURP2
                               )

        engines[domain] = engine

    for (domain, engine) in engines.items():
        engine.queue(req, [domain.rstrip(), domain.rstrip()])


def handleResponse(req, interesting):

    if 'HTTP' in req.response:

        table.add(req)

```
So First Issue I Faced Is If I Added pseudo-header  :method: GET Instead Of GET / HTTP/2 

![Screenshot_2021-09-03_11_53_31](https://user-images.githubusercontent.com/54332136/131988144-99702cc2-864a-4e09-b46a-62329dafdbbb.jpg)

Burp Suite Will Not Handle This Correctly , It Will Set :method pseudo-header Value :method: AND :path pseudo-header Value GET:authority: Like This 

![Screenshot_2021-09-03_11_57_42](https://user-images.githubusercontent.com/54332136/131988184-2f0bf532-b69e-44ce-afae-65cc1341e9e7.jpg)

So After Alot Of Times Trying Solving This One , I Solved By Set This Line GET / HTTP/2 Then Try To Use Addition pseudo-header to Override The Method 

![Screenshot_2021-09-03_12_08_41](https://user-images.githubusercontent.com/54332136/131989020-6b22a71b-ab46-40db-a7f5-ebc81c88c9a0.jpg)

### But All Of This Work Only If My Wordlist Very Very Small 

### And If I Used Wordlist Contains e.g. 30K subdomains Burp Suite Will Crash 

So Can You Debug This OR That Normal Behavior AND I Can't Use Turps-Intruder To Send a Single Request To a Lot Of Hosts ?
Plus It's Possible To Write The Whole Request By Using Pseudo-Header ?

Thanks In Advanced

**Comment by albinowax** [comment]
Sorry, this is a design limitation and explicity mentioned in the readme:

> it's designed for sending lots of requests to a single host. If you want to send a single request to a lot of hosts, I recommend ZGrab

https://github.com/PortSwigger/turbo-intruder

**Comment by albinowax** [comment]
If you want to scan for H/2 attacks I recommend using HTTP Request Smuggler
