### ISSUE TITLE
TI not sending requests

### ISSUE THREAD

**Issue by adrian-rt** [PortSwigger/turbo-intruder#87]
I've queued in my my TI script about 3-10 requests. it seems that they all fail somehow regardless if I'm using HTTP1/HTTP2.

If I'm using HTTP 2, I get proxy_fcgi error in my apache error log + SERVER sent a RST stream, dumping the whole conneciton.

If I'm usign http1 I get null pointer exception. nothing in the error log. The access logs contain a lot of 408 errors.

I've added a ProxyTimeout 300 in httpd.conf.

Please see attached screenshots for more stats from TI.

thanks.

![Screenshot from 2021-10-29 19-16-24](https://user-images.githubusercontent.com/1128817/139483749-0fc5ee2d-6868-4a58-be49-d43236c15252.png)
![Screenshot from 2021-10-29 19-16-33](https://user-images.githubusercontent.com/1128817/139483753-37e8e5dd-11f7-4833-b0ac-8c11b39a7ecf.png)
![Screenshot from 2021-10-29 19-17-39](https://user-images.githubusercontent.com/1128817/139483755-dd962f99-e061-4371-acb8-557d28d849af.png)

**Comment by albinowax** [comment]
Can you share your full script, the request including the target, and the turbo intruder version?
