### ISSUE TITLE
Callback to Stop Turbo Intruder

### ISSUE THREAD

**Issue by wdahlenburg** [PortSwigger/turbo-intruder#91]
It would be helpful to be able to have a callable function to signal that the turbo-intruder script can exit. This is useful for bruteforcing a large keyspace and exiting upon a certain condition.

Take the following for example where I'd like to stop the attack once I receive a 302 status code:
```
def handleResponse(req, interesting):
    if req.status == 302:
        table.add(req)
        complete()
```
The `engine.complete()` function currently shows stats but doesn't exit out: https://github.com/PortSwigger/turbo-intruder/blob/master/resources/ScriptEnvironment.py#L323. The [race.py](https://github.com/PortSwigger/turbo-intruder/blob/master/resources/examples/race.py) script currently makes use of this function.

It seems like there are a few places that allow for the GUI and Kotlin code to stop the script, but it seems like this is missing from within the python RequestEngine.

Would it make sense to add the logic to exit the attack in the current ScriptEnvironment.py complete function or should it be somewhere else?

**Comment by albinowax** [comment]
I'll add engine.cancel() in the next release. For now, engine.engine.cancel() should do the trick

**Comment by wdahlenburg** [comment]
I'm seeing the following in the logs after adding `engine.engine.cancel()` to the handleResponse function:

```
Error in user-defined callback: Traceback (most recent call last):
  File "<string>", line 17, in handleResponse
NameError: global name 'engine' is not defined
```

This makes sense because engine is defined in queueRequests. Python asks for it to be global because it's not accessible as a parameter. Trying to set it globally by adding `engine = None` to the top gives the following:

```
Error in user-defined callback: Traceback (most recent call last):
  File "<string>", line 18, in handleResponse
AttributeError: 'NoneType' object has no attribute 'engine'
```

`engine.engine.cancel()` does work within the queueRequests function. I haven't seen a way to query current results from within this function though.

---
Should engine be included as a parameter in the callback function handleResponse?

**Comment by albinowax** [comment]
Try req.engine.cancel()

**Comment by wdahlenburg** [comment]
That works. Thanks. Do you want me to close this issue out or leave it open for a small helper function?

**Comment by albinowax** [comment]
Great. Let's leave it open, I'll push a fix in a bit.
