### ISSUE TITLE
How to I identify, how many payload markers(%s) are in target.req?

### ISSUE THREAD

**Issue by thedarksource** [PortSwigger/turbo-intruder#95]
I want to fuzz multiple parameters by dynamically identifying the number of payload markers(%s) in request.

ex.
```
POST /details%s HTTP/1.1
Host: example.com%s
Content-Type: application/json
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36

{
    "name": "morpheus%s",
    "job": "leader%s",
    "salary%s": "10000",
}
```
Here, I want my script to identify how many payload markers(%s) are there in `target.req`, and based on that I want to fuzz all the parameters with my wordlist.

**Comment by albinowax** [comment]
Try something like target.req.count('%s')
