### ISSUE TITLE
decode request error,cause:java.lang.IllegalArgumentException: invalid version format: HTTP/2

### ISSUE THREAD

**Issue by bobipoppy** [PortSwigger/turbo-intruder#98]
![image](https://user-images.githubusercontent.com/50575997/163092925-8b02abd8-c06d-4c52-875f-4277e778ba86.png)
I can't use it under the http2.0 protocol. Do you want to ask if there is any solution?

**Comment by albinowax** [comment]
Try BURP2 instead
